services:
 web:
  image: nginx:latest
  container_name: nginx
  restart: always
  ports:
   - "80:80"
  volumes:
   - ./app:/app
   - ./site.conf:/etc/nginx/conf.d/site.conf
  links:
  - php
 php:
  build: .
  container_name: php-fpm
  volumes:
  - ./app:/app
  links:
  - db
 db:
  image: mysql:5.7
  container_name: mysql
  ports:
  - "3306:3306"
  command: --default-authentication-plugin=mysql_native_password
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: dev1234
    MYSQL_DATABASE: bd-automoveis